require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ElementPrototypesController do

  # This should return the minimal set of attributes required to create a valid
  # ElementPrototype. As you add validations to ElementPrototype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ElementPrototypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all element_prototypes as @element_prototypes" do
      element_prototype = ElementPrototype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:element_prototypes).should eq([element_prototype])
    end
  end

  describe "GET show" do
    it "assigns the requested element_prototype as @element_prototype" do
      element_prototype = ElementPrototype.create! valid_attributes
      get :show, {:id => element_prototype.to_param}, valid_session
      assigns(:element_prototype).should eq(element_prototype)
    end
  end

  describe "GET new" do
    it "assigns a new element_prototype as @element_prototype" do
      get :new, {}, valid_session
      assigns(:element_prototype).should be_a_new(ElementPrototype)
    end
  end

  describe "GET edit" do
    it "assigns the requested element_prototype as @element_prototype" do
      element_prototype = ElementPrototype.create! valid_attributes
      get :edit, {:id => element_prototype.to_param}, valid_session
      assigns(:element_prototype).should eq(element_prototype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ElementPrototype" do
        expect {
          post :create, {:element_prototype => valid_attributes}, valid_session
        }.to change(ElementPrototype, :count).by(1)
      end

      it "assigns a newly created element_prototype as @element_prototype" do
        post :create, {:element_prototype => valid_attributes}, valid_session
        assigns(:element_prototype).should be_a(ElementPrototype)
        assigns(:element_prototype).should be_persisted
      end

      it "redirects to the created element_prototype" do
        post :create, {:element_prototype => valid_attributes}, valid_session
        response.should redirect_to(ElementPrototype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved element_prototype as @element_prototype" do
        # Trigger the behavior that occurs when invalid params are submitted
        ElementPrototype.any_instance.stub(:save).and_return(false)
        post :create, {:element_prototype => { "name" => "invalid value" }}, valid_session
        assigns(:element_prototype).should be_a_new(ElementPrototype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ElementPrototype.any_instance.stub(:save).and_return(false)
        post :create, {:element_prototype => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested element_prototype" do
        element_prototype = ElementPrototype.create! valid_attributes
        # Assuming there are no other element_prototypes in the database, this
        # specifies that the ElementPrototype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ElementPrototype.any_instance.should_receive(:update_attributes).with({ "name" => "" })
        put :update, {:id => element_prototype.to_param, :element_prototype => { "name" => "" }}, valid_session
      end

      it "assigns the requested element_prototype as @element_prototype" do
        element_prototype = ElementPrototype.create! valid_attributes
        put :update, {:id => element_prototype.to_param, :element_prototype => valid_attributes}, valid_session
        assigns(:element_prototype).should eq(element_prototype)
      end

      it "redirects to the element_prototype" do
        element_prototype = ElementPrototype.create! valid_attributes
        put :update, {:id => element_prototype.to_param, :element_prototype => valid_attributes}, valid_session
        response.should redirect_to(element_prototype)
      end
    end

    describe "with invalid params" do
      it "assigns the element_prototype as @element_prototype" do
        element_prototype = ElementPrototype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ElementPrototype.any_instance.stub(:save).and_return(false)
        put :update, {:id => element_prototype.to_param, :element_prototype => { "name" => "invalid value" }}, valid_session
        assigns(:element_prototype).should eq(element_prototype)
      end

      it "re-renders the 'edit' template" do
        element_prototype = ElementPrototype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ElementPrototype.any_instance.stub(:save).and_return(false)
        put :update, {:id => element_prototype.to_param, :element_prototype => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested element_prototype" do
      element_prototype = ElementPrototype.create! valid_attributes
      expect {
        delete :destroy, {:id => element_prototype.to_param}, valid_session
      }.to change(ElementPrototype, :count).by(-1)
    end

    it "redirects to the element_prototypes list" do
      element_prototype = ElementPrototype.create! valid_attributes
      delete :destroy, {:id => element_prototype.to_param}, valid_session
      response.should redirect_to(element_prototypes_url)
    end
  end

end
