require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FlowsController do

  # This should return the minimal set of attributes required to create a valid
  # Flow. As you add validations to Flow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FlowsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all flows as @flows" do
      flow = Flow.create! valid_attributes
      get :index, {}, valid_session
      assigns(:flows).should eq([flow])
    end
  end

  describe "GET show" do
    it "assigns the requested flow as @flow" do
      flow = Flow.create! valid_attributes
      get :show, {:id => flow.to_param}, valid_session
      assigns(:flow).should eq(flow)
    end
  end

  describe "GET new" do
    it "assigns a new flow as @flow" do
      get :new, {}, valid_session
      assigns(:flow).should be_a_new(Flow)
    end
  end

  describe "GET edit" do
    it "assigns the requested flow as @flow" do
      flow = Flow.create! valid_attributes
      get :edit, {:id => flow.to_param}, valid_session
      assigns(:flow).should eq(flow)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Flow" do
        expect {
          post :create, {:flow => valid_attributes}, valid_session
        }.to change(Flow, :count).by(1)
      end

      it "assigns a newly created flow as @flow" do
        post :create, {:flow => valid_attributes}, valid_session
        assigns(:flow).should be_a(Flow)
        assigns(:flow).should be_persisted
      end

      it "redirects to the created flow" do
        post :create, {:flow => valid_attributes}, valid_session
        response.should redirect_to(Flow.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved flow as @flow" do
        # Trigger the behavior that occurs when invalid params are submitted
        Flow.any_instance.stub(:save).and_return(false)
        post :create, {:flow => { "name" => "invalid value" }}, valid_session
        assigns(:flow).should be_a_new(Flow)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Flow.any_instance.stub(:save).and_return(false)
        post :create, {:flow => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested flow" do
        flow = Flow.create! valid_attributes
        # Assuming there are no other flows in the database, this
        # specifies that the Flow created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Flow.any_instance.should_receive(:update_attributes).with({ "name" => "" })
        put :update, {:id => flow.to_param, :flow => { "name" => "" }}, valid_session
      end

      it "assigns the requested flow as @flow" do
        flow = Flow.create! valid_attributes
        put :update, {:id => flow.to_param, :flow => valid_attributes}, valid_session
        assigns(:flow).should eq(flow)
      end

      it "redirects to the flow" do
        flow = Flow.create! valid_attributes
        put :update, {:id => flow.to_param, :flow => valid_attributes}, valid_session
        response.should redirect_to(flow)
      end
    end

    describe "with invalid params" do
      it "assigns the flow as @flow" do
        flow = Flow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Flow.any_instance.stub(:save).and_return(false)
        put :update, {:id => flow.to_param, :flow => { "name" => "invalid value" }}, valid_session
        assigns(:flow).should eq(flow)
      end

      it "re-renders the 'edit' template" do
        flow = Flow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Flow.any_instance.stub(:save).and_return(false)
        put :update, {:id => flow.to_param, :flow => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested flow" do
      flow = Flow.create! valid_attributes
      expect {
        delete :destroy, {:id => flow.to_param}, valid_session
      }.to change(Flow, :count).by(-1)
    end

    it "redirects to the flows list" do
      flow = Flow.create! valid_attributes
      delete :destroy, {:id => flow.to_param}, valid_session
      response.should redirect_to(flows_url)
    end
  end

end
