require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeasuresController do

  # This should return the minimal set of attributes required to create a valid
  # Measure. As you add validations to Measure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "timeStamp" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeasuresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all measures as @measures" do
      measure = Measure.create! valid_attributes
      get :index, {}, valid_session
      assigns(:measures).should eq([measure])
    end
  end

  describe "GET show" do
    it "assigns the requested measure as @measure" do
      measure = Measure.create! valid_attributes
      get :show, {:id => measure.to_param}, valid_session
      assigns(:measure).should eq(measure)
    end
  end

  describe "GET new" do
    it "assigns a new measure as @measure" do
      get :new, {}, valid_session
      assigns(:measure).should be_a_new(Measure)
    end
  end

  describe "GET edit" do
    it "assigns the requested measure as @measure" do
      measure = Measure.create! valid_attributes
      get :edit, {:id => measure.to_param}, valid_session
      assigns(:measure).should eq(measure)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Measure" do
        expect {
          post :create, {:measure => valid_attributes}, valid_session
        }.to change(Measure, :count).by(1)
      end

      it "assigns a newly created measure as @measure" do
        post :create, {:measure => valid_attributes}, valid_session
        assigns(:measure).should be_a(Measure)
        assigns(:measure).should be_persisted
      end

      it "redirects to the created measure" do
        post :create, {:measure => valid_attributes}, valid_session
        response.should redirect_to(Measure.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved measure as @measure" do
        # Trigger the behavior that occurs when invalid params are submitted
        Measure.any_instance.stub(:save).and_return(false)
        post :create, {:measure => { "timeStamp" => "invalid value" }}, valid_session
        assigns(:measure).should be_a_new(Measure)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Measure.any_instance.stub(:save).and_return(false)
        post :create, {:measure => { "timeStamp" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested measure" do
        measure = Measure.create! valid_attributes
        # Assuming there are no other measures in the database, this
        # specifies that the Measure created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Measure.any_instance.should_receive(:update_attributes).with({ "timeStamp" => "" })
        put :update, {:id => measure.to_param, :measure => { "timeStamp" => "" }}, valid_session
      end

      it "assigns the requested measure as @measure" do
        measure = Measure.create! valid_attributes
        put :update, {:id => measure.to_param, :measure => valid_attributes}, valid_session
        assigns(:measure).should eq(measure)
      end

      it "redirects to the measure" do
        measure = Measure.create! valid_attributes
        put :update, {:id => measure.to_param, :measure => valid_attributes}, valid_session
        response.should redirect_to(measure)
      end
    end

    describe "with invalid params" do
      it "assigns the measure as @measure" do
        measure = Measure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Measure.any_instance.stub(:save).and_return(false)
        put :update, {:id => measure.to_param, :measure => { "timeStamp" => "invalid value" }}, valid_session
        assigns(:measure).should eq(measure)
      end

      it "re-renders the 'edit' template" do
        measure = Measure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Measure.any_instance.stub(:save).and_return(false)
        put :update, {:id => measure.to_param, :measure => { "timeStamp" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested measure" do
      measure = Measure.create! valid_attributes
      expect {
        delete :destroy, {:id => measure.to_param}, valid_session
      }.to change(Measure, :count).by(-1)
    end

    it "redirects to the measures list" do
      measure = Measure.create! valid_attributes
      delete :destroy, {:id => measure.to_param}, valid_session
      response.should redirect_to(measures_url)
    end
  end

end
