require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TriggersController do

  # This should return the minimal set of attributes required to create a valid
  # Trigger. As you add validations to Trigger, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TriggersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all triggers as @triggers" do
      trigger = Trigger.create! valid_attributes
      get :index, {}, valid_session
      assigns(:triggers).should eq([trigger])
    end
  end

  describe "GET show" do
    it "assigns the requested trigger as @trigger" do
      trigger = Trigger.create! valid_attributes
      get :show, {:id => trigger.to_param}, valid_session
      assigns(:trigger).should eq(trigger)
    end
  end

  describe "GET new" do
    it "assigns a new trigger as @trigger" do
      get :new, {}, valid_session
      assigns(:trigger).should be_a_new(Trigger)
    end
  end

  describe "GET edit" do
    it "assigns the requested trigger as @trigger" do
      trigger = Trigger.create! valid_attributes
      get :edit, {:id => trigger.to_param}, valid_session
      assigns(:trigger).should eq(trigger)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Trigger" do
        expect {
          post :create, {:trigger => valid_attributes}, valid_session
        }.to change(Trigger, :count).by(1)
      end

      it "assigns a newly created trigger as @trigger" do
        post :create, {:trigger => valid_attributes}, valid_session
        assigns(:trigger).should be_a(Trigger)
        assigns(:trigger).should be_persisted
      end

      it "redirects to the created trigger" do
        post :create, {:trigger => valid_attributes}, valid_session
        response.should redirect_to(Trigger.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trigger as @trigger" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trigger.any_instance.stub(:save).and_return(false)
        post :create, {:trigger => { "name" => "invalid value" }}, valid_session
        assigns(:trigger).should be_a_new(Trigger)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trigger.any_instance.stub(:save).and_return(false)
        post :create, {:trigger => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trigger" do
        trigger = Trigger.create! valid_attributes
        # Assuming there are no other triggers in the database, this
        # specifies that the Trigger created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Trigger.any_instance.should_receive(:update_attributes).with({ "name" => "" })
        put :update, {:id => trigger.to_param, :trigger => { "name" => "" }}, valid_session
      end

      it "assigns the requested trigger as @trigger" do
        trigger = Trigger.create! valid_attributes
        put :update, {:id => trigger.to_param, :trigger => valid_attributes}, valid_session
        assigns(:trigger).should eq(trigger)
      end

      it "redirects to the trigger" do
        trigger = Trigger.create! valid_attributes
        put :update, {:id => trigger.to_param, :trigger => valid_attributes}, valid_session
        response.should redirect_to(trigger)
      end
    end

    describe "with invalid params" do
      it "assigns the trigger as @trigger" do
        trigger = Trigger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trigger.any_instance.stub(:save).and_return(false)
        put :update, {:id => trigger.to_param, :trigger => { "name" => "invalid value" }}, valid_session
        assigns(:trigger).should eq(trigger)
      end

      it "re-renders the 'edit' template" do
        trigger = Trigger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trigger.any_instance.stub(:save).and_return(false)
        put :update, {:id => trigger.to_param, :trigger => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trigger" do
      trigger = Trigger.create! valid_attributes
      expect {
        delete :destroy, {:id => trigger.to_param}, valid_session
      }.to change(Trigger, :count).by(-1)
    end

    it "redirects to the triggers list" do
      trigger = Trigger.create! valid_attributes
      delete :destroy, {:id => trigger.to_param}, valid_session
      response.should redirect_to(triggers_url)
    end
  end

end
